version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-sample-deploy
permissions:
  - object: /home/ubuntu/aws-sample-deploy
    owner: ubuntu
    group: ubuntu
    pattern: "*"
    mode: 775
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deployment_scripts/arrange_deployment_folders.sh
      runas: ubuntu
  AfterInstall:
    - location: deployment_scripts/bundle_and_compile_resources.sh
      runas: ubuntu

  ApplicationStart:
    - location: deployment_scripts/restart_services.sh
      runas: ubuntu





